'use strict';

/**
 * Clôture mensuelle en 1 clic — idempotente et déterministe.
 * Réutilise la logique commune (factures brouillon, relances, P&L, tournées).
 */

const invoicing = require('./invoicing');
const templates = require('./templates');
const pnl = require('./pnl');
const tours = require('./tours');

function r2(n) { return Math.round((n || 0) * 100) / 100; }

/**
 * Génère les factures brouillon des contrats actifs pour `period` (idempotent).
 * commit=false => dry-run (ne persiste pas, restaure le compteur).
 */
function draftInvoicesForPeriod(data, period, commit) {
  const seq0 = data.erp.invoiceSeq || 0;
  const created = [];
  for (const c of (data.contracts || [])) {
    if (c.active === false) continue;
    const client = c.client || c.name || 'Donneur d\'ordre';
    const exists = data.erp.invoices.some((i) => i.client === client && i.period === period);
    if (exists) continue;
    const inv = invoicing.buildInvoice(data, {
      client, clientAddress: c.address || '', period,
      lines: [{ designation: `Prestation de livraison — ${period}`, quantite: 1, prixUnitaire: Number(c.monthlyAmount) || 0 }],
    });
    inv.autoGenerated = true;
    if (commit) data.erp.invoices.push(inv);
    created.push(inv);
  }
  if (!commit) data.erp.invoiceSeq = seq0; // numérotation rétablie en mode aperçu
  return created;
}

function runMonthlyClosing(data, ym, opts = {}) {
  const preview = !!opts.preview;
  const commit = !preview;
  const now = opts.now || new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString().slice(0, 10);

  // 1) Factures brouillon des contrats actifs.
  const draftInvoices = draftInvoicesForPeriod(data, ym, commit).map((i) => ({ number: i.number, client: i.client, totalTTC: i.totalTTC, period: i.period }));

  // 2) Factures échues impayées + relances (publipostage).
  const co = data.settings.company || {};
  const overdue = (data.erp.invoices || []).filter((i) => i.status === 'sent' && i.dueDate && i.dueDate < today);
  const relances = overdue.map((i) => ({
    number: i.number, client: i.client, totalTTC: i.totalTTC, dueDate: i.dueDate,
    html: templates.render(data.settings.erpTemplates.relance.body, {
      company: co, date: new Date(now).toLocaleDateString('fr-FR'),
      client: { name: i.client, address: i.clientAddress || '' },
      invoice: { number: i.number, date: i.date, totalTTC: i.totalTTC, dueDate: i.dueDate },
    }),
  }));

  // 3) Paie variable du mois (heures travaillées depuis workHours).
  const payroll = {};
  for (const h of (data.workHours || [])) {
    if (String(h.date || '').slice(0, 7) !== ym) continue;
    const o = payroll[h.userId] || (payroll[h.userId] = { userId: h.userId, userName: h.userName, days: 0, worked: 0, amplitude: 0, nightHours: 0 });
    o.days += 1; o.worked += Number(h.worked) || 0; o.amplitude += Number(h.amplitude) || 0; o.nightHours += Number(h.nightHours) || 0;
  }
  const payrollRows = Object.values(payroll).map((o) => ({ ...o, worked: r2(o.worked), amplitude: r2(o.amplitude), nightHours: r2(o.nightHours) }));

  // 4) Récapitulatif financier.
  const p = pnl.computePnL(data, ym);
  const toursTot = tours.analytics(data, { ym }).totals;
  const aEncaisser = r2((data.erp.invoices || []).filter((i) => i.status === 'sent').reduce((s, i) => s + (Number(i.totalTTC) || 0), 0));

  return {
    ym, preview,
    draftInvoices,
    overdue: relances,
    payroll: payrollRows,
    recap: { ca: p.ca, charges: p.charges, resultat: p.result, margeTournees: toursTot.marge, aEncaisser },
  };
}

module.exports = { runMonthlyClosing, draftInvoicesForPeriod };
