'use strict';

/**
 * Tâches planifiées — la seconde moitié de l'« auto-pilote ».
 * Le système agit seul à intervalles réguliers, sans aucune IA.
 *
 * node-cron est optionnel : s'il n'est pas installé, on se rabat sur setInterval
 * (l'application démarre normalement dans tous les cas).
 *
 * À n'activer que sur un serveur permanent (OVH/VPS/Render), pas en serverless.
 */

const pnl = require('./pnl');
const rules = require('./rules');

function start(deps) {
  const { getData, save } = deps;
  let cron = null;
  try { cron = require('node-cron'); } catch (e) { /* fallback ci-dessous */ }

  const tasks = [
    { name: 'digest-matin', cron: '0 7 * * *', fn: () => buildDigest(getData, save) },
    { name: 'recalc-nuit', cron: '0 2 * * *', fn: () => nightlyRecalc(getData, save) },
    { name: 'factures-mensuelles', cron: '0 6 1 * *', fn: () => monthlyDraftInvoices(getData, save) },
  ];

  if (cron) {
    for (const t of tasks) cron.schedule(t.cron, t.fn, { timezone: 'Europe/Paris' });
    console.log('ERP : tâches planifiées actives (node-cron) —', tasks.map((t) => t.name).join(', '));
  } else {
    // Fallback minimal : on construit le digest une fois par heure.
    setInterval(() => buildDigest(getData, save), 3600 * 1000);
    console.log('ERP : node-cron absent — digest horaire via setInterval. (npm i node-cron pour le planning complet.)');
  }
}

/** Snapshot des échéances du jour (alertes critiques/urgentes). */
async function buildDigest(getData, save) {
  try {
    const data = getData();
    require('./index').ensureErp(data);
    const alerts = rules.computeAlerts(data).filter((a) => a.level !== 'info');
    data.erp.digests.unshift({ date: new Date().toISOString().slice(0, 10), count: alerts.length, alerts });
    data.erp.digests = data.erp.digests.slice(0, 30);
    await save();
  } catch (e) { console.error('ERP digest:', e.message); }
}

async function nightlyRecalc(getData, save) {
  try {
    const data = getData();
    require('./index').ensureErp(data);
    // Place réservée : recalculs nocturnes (soldes, agrégats…). On persiste un
    // horodatage pour preuve d'exécution.
    data.erp._lastRecalc = new Date().toISOString();
    await save();
  } catch (e) { console.error('ERP recalc:', e.message); }
}

/** Le 1er du mois : prépare des factures BROUILLON pour les contrats actifs. */
async function monthlyDraftInvoices(getData, save) {
  try {
    const data = getData();
    require('./index').ensureErp(data);
    const invoicing = require('./invoicing');
    const prev = new Date(); prev.setDate(0); // dernier jour du mois précédent
    const period = `${prev.getFullYear()}-${String(prev.getMonth() + 1).padStart(2, '0')}`;

    for (const c of (data.contracts || [])) {
      if (c.active === false) continue;
      // Évite les doublons : une seule facture brouillon par contrat et période.
      const exists = data.erp.invoices.some((i) => i.client === (c.client || c.name) && i.period === period);
      if (exists) continue;
      const inv = invoicing.buildInvoice(data, {
        client: c.client || c.name || 'Donneur d\'ordre',
        clientAddress: c.address || '',
        period,
        lines: [{ designation: `Prestation de livraison — ${period}`, quantite: 1, prixUnitaire: Number(c.monthlyAmount) || 0 }],
      });
      inv.autoGenerated = true;
      data.erp.invoices.push(inv);
    }
    await save();
    console.log('ERP : factures brouillon générées pour', period);
  } catch (e) { console.error('ERP factures mensuelles:', e.message); }
}

module.exports = { start };
